project_name: terminus-cli

before:
  hooks:
  - go mod tidy


builds:
- id: linux_amd64
  env:
  - CGO_ENABLED=1
  - GOOS=linux
  - GOARCH=amd64
  - CC=x86_64-linux-musl-gcc
  - CGO_LDFLAGS=-static
  goos:
  - linux
  goarch:
  - amd64
  ldflags:
  - -w
  - -s
  binary: terminus-cli
  main: ./cmd/main.go
- id: linux_arm
  env:
  - CGO_ENABLED=1
  - GOOS=linux
  - GOARCH=arm
  - GOARM=7
  - CC=arm-linux-gnueabihf-gcc
  - CXX=arm-linux-gnueabihf-g++
  goos:
  - linux
  goarch:
  - arm
  goarm:
  - 7
  ldflags:
  - -w
  - -s
  binary: terminus-cli
  main: ./cmd/main.go

dist: ./output
archives:
- id: terminus-cli
  name_template: "{{ .ProjectName }}-v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  replacements:
    linux: linux
    amd64: amd64
    arm: armv7
  files:
  - none*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}-next-{{.ShortCommit}}"
changelog:
  skip: true
  sort: asc
  filters:
    exclude:
    - "^docs:"
    - "^test:"
