CREATE TABLE IF NOT EXISTS install_logs (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    message VARCHAR(512) NOT NULL,
    state VARCHAR(100) NOT NULL,
    percent INTEGER DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);